### ISSUE TITLE
dead Links

### ISSUE THREAD

**Issue by bvaisman-GitHub** [Symbitic/awesome-babylonjs#1]
Hi,

This project is great with many useful examples. I use it very often when i want a piece of code.

But the Github links to the demos and the scenes are dead maybe because you moved the entire project. It could be great to "revive" them.

Thanks in advance,

Boris

**Comment by Symbitic** [comment]
@bvaisman-GitHub Thanks for pointing that out. I fixed the links for the demos and scenes. Hope you find it useful.
